name: HoloDex
options:
  xcodeVersion: 10.0
  deploymentTarget:
    iOS: 13.0
  bundleIdPrefix: io.lewismorgan.HoloDex
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  groupSortPosition: top
configs:
  # Local Development | Development certs - Staging (Pull Requests)
  Debug: debug
  # Ad Hoc Development | Ad Hoc profile w/ Distribution Certs - Staging (develop)
  Beta: beta
  # Release builds | Archiving a production build (master)
  Release: release
configFiles:
  Debug: Configs/Debug.xcconfig
  Beta: Configs/Beta.xcconfig
  Release: Configs/Release.xcconfig
targets:
  HoloDex:
    platform: iOS
    type: application
    sources:
      - HoloDex
      - path: HoloDex/Resources/Assets.generated.swift
        optional: true
      - path: HoloDex/Resources/Fonts.generated.swift
        optional: true
      - path: HoloDex/Resources/Scenes.generated.swift
        optional: true
    scheme:
      testTargets:
        - UnitTests
    configFiles:
      Debug: Configs/HoloDex-Debug.xcconfig
      Beta: Configs/HoloDex-Beta.xcconfig
      Release: Configs/HoloDex-Release.xcconfig
    preBuildScripts:
      - script: swiftgen
        name: Swiftgen
        inputFiles:
          - $SRCROOT/swiftgen.yml
        outputFiles:
          - $SRCROOT/HoloDex/Resources/Generated/Assets.swift
          - $SRCROOT/HoloDex/Resources/Generated/Fonts.swift
          - $SRCROOT/HoloDex/Resources/Generated/Scenes.swift
    postCompileScripts:
      - script: if [ -z "$CI" ]; then swiftlint; fi
        name: SwiftLint
    dependencies:
      - carthage: Alamofire
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxBlocking
      - carthage: RxAlamofire
      - carthage: ObjectMapper
      - carthage: RxDataSources
      - carthage: Differentiator
      - carthage: Swinject
  UnitTests:
    type: bundle.unit-test
    platform: iOS
    sources: UnitTests
    configFiles:
      Debug: Configs/UnitTests.xcconfig
      Beta: Configs/UnitTests.xcconfig
      Release: Configs/UnitTests.xcconfig
    scheme:
      testTargets:
        - UnitTests
    dependencies:
      - target: HoloDex