platform :ios, '10.0'

target 'HoloDex' do
  use_frameworks!

  # Pods for HoloDex
  pod 'ObjectMapper', :inhibit_warnings => true
  pod 'Alamofire'
  pod 'AlamofireObjectMapper', :inhibit_warnings => true
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ReSwift'
  pod 'ReSwiftRouter'
  pod 'PinLayout'
  pod 'FlexLayout'

  target 'HoloDexUnitTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'RxTest'
    pod 'RxBlocking'
    pod 'RxNimble'
  end
end
