platform :ios, '12.1'
use_frameworks!
workspace 'HoloDex'

def corePods
  pod 'RxSwift', '~> 4.0'
  pod 'ObjectMapper', '~> 3.0'
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 5.0'
end

def uiPods
  pod 'RxCocoa', '~> 4.0'
  pod 'ReSwift', '~> 4.0'
  pod 'ReSwiftRouter', '~> 0.5'
  pod 'PinLayout', '~> 1.0'
  pod 'FlexLayout', '~> 1.0'
end

def testingPods
  pod 'Quick', '~> 1.3'
  pod 'Nimble', '~> 7.0'
  pod 'RxTest', '~> 4.0'
end

target 'Core' do
  project 'Core/Core'
  corePods
  target 'CoreTests' do
    inherit! :search_paths
    testingPods
  end
end

target 'People' do
  project 'People/People'
  corePods
  target 'PeopleTests' do
    inherit! :search_paths
    testingPods
  end
end

target 'HoloDex' do
  corePods
  uiPods
end
