platform :ios, '10.0'
use_frameworks!
workspace 'HoloDex'

def corePods
  pod 'RxSwift'
  pod 'ObjectMapper', :inhibit_warnings => true
  pod 'Alamofire'
  pod 'AlamofireObjectMapper', :inhibit_warnings => true
end

def uiPods
  pod 'RxCocoa'
  pod 'ReSwift'
  pod 'ReSwiftRouter'
  pod 'PinLayout'
  pod 'FlexLayout'
end

def testingPods
  pod 'Quick'
  pod 'Nimble'
  pod 'RxTest'
  pod 'RxBlocking'
  pod 'RxNimble'
end

target 'Core' do
  project 'Core/Core'
  corePods
  target 'CoreTests' do
    inherit! :search_paths
    testingPods
  end
end

target 'People' do
  project 'People/People'
  corePods
  target 'PeopleTests' do
    inherit! :search_paths
    testingPods
  end
end

target 'HoloDex' do
  corePods
  uiPods
end
